# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumreply',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
