# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_forums', '0002_auto_20190211_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='url',
            field=models.URLField(blank=True, help_text='Optional link to external content.', verbose_name='External content'),
        ),
    ]
