# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 03:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import pinax.forums.models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_forums', '0003_forumthread_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='pdf',
            field=models.FileField(blank=True, help_text='Optional.', null=True, upload_to='pdfs', validators=[django.core.validators.FileExtensionValidator(['pdf']), pinax.forums.models.pdf_only], verbose_name='A PDF file with additional information'),
        ),
    ]
